import { motion } from "framer-motion";
import {
  FaHeartbeat,
  FaClock,
  FaUserMd,
  FaNotesMedical,
} from "react-icons/fa";

export default function AboutECG() {
  const features = [
    {
      icon: <FaHeartbeat />,
      title: "Heart Monitoring",
      description:
        "ECG records the electrical activity of your heart and helps detect irregular rhythms.",
    },
    {
      icon: <FaClock />,
      title: "Quick Procedure",
      description:
        "The ECG test usually takes only 5 to 10 minutes and is completely painless.",
    },
    {
      icon: <FaUserMd />,
      title: "Expert Analysis",
      description:
        "Experienced cardiologists carefully review your ECG results.",
    },
    {
      icon: <FaNotesMedical />,
      title: "Accurate Report",
      description:
        "Get detailed digital reports for better diagnosis and treatment.",
    },
  ];

  return (
    <section className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-5">

        {/* Heading */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          viewport={{ once: true }}
          className="text-center max-w-3xl mx-auto"
        >
          <span className="bg-blue-100 text-blue-600 px-4 py-2 rounded-full font-semibold">
            About ECG Test
          </span>

          <h2 className="text-4xl md:text-5xl font-bold text-gray-800 mt-5">
            What is an ECG?
          </h2>

          <p className="mt-5 text-gray-600 leading-8">
            An Electrocardiogram (ECG) is a medical test that measures the
            electrical signals generated by your heart. It helps doctors
            understand heart rhythm, detect abnormalities, and evaluate
            overall cardiac health.
          </p>
        </motion.div>


        {/* Main Content */}
        <div className="grid lg:grid-cols-2 gap-12 items-center mt-16">

          {/* Left Image */}
          <motion.div
            initial={{ opacity: 0, x: -60 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
          >
            <img
              src="https://images.unsplash.com/photo-1551076805-e1869033e561?w=900"
              alt="ECG Test"
              className="rounded-3xl shadow-xl w-full"
            />
          </motion.div>


          {/* Right Content */}
          <motion.div
            initial={{ opacity: 0, x: 60 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8 }}
            viewport={{ once: true }}
          >

            <h3 className="text-3xl font-bold text-gray-800 mb-5">
              Why ECG Test is Important?
            </h3>

            <p className="text-gray-600 leading-8 mb-6">
              ECG helps identify heart-related problems at an early stage.
              It is commonly recommended for chest pain, irregular heartbeat,
              breathing problems, and routine heart check-ups.
            </p>


            <ul className="space-y-4 text-gray-700">

              <li className="flex gap-3 items-center">
                <span className="text-green-500 text-xl">✔</span>
                Detect abnormal heart rhythms
              </li>

              <li className="flex gap-3 items-center">
                <span className="text-green-500 text-xl">✔</span>
                Evaluate heart health condition
              </li>

              <li className="flex gap-3 items-center">
                <span className="text-green-500 text-xl">✔</span>
                Monitor treatment progress
              </li>

              <li className="flex gap-3 items-center">
                <span className="text-green-500 text-xl">✔</span>
                Helps in early diagnosis
              </li>

            </ul>

          </motion.div>

        </div>


        {/* Feature Cards */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 mt-16">

          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              viewport={{ once: true }}
              whileHover={{ y: -8 }}
              className="bg-gray-50 rounded-2xl p-6 text-center shadow-md hover:shadow-xl transition"
            >

              <div className="text-4xl text-blue-600 flex justify-center mb-4">
                {feature.icon}
              </div>

              <h4 className="text-xl font-bold text-gray-800">
                {feature.title}
              </h4>

              <p className="text-gray-600 mt-3 text-sm leading-6">
                {feature.description}
              </p>

            </motion.div>
          ))}

        </div>

      </div>
    </section>
  );
}